apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: siteassignment
  labels:
    app: mysql
data:
  master.cnf: |
    # Master configuration
    [mysqld]
    log-bin
  slave.cnf: |
    # Slave configuration
    [mysqld]
    super-read-only